<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFiBxwqx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFiBxwqx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFiBxwqx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFiBxwqx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFiBxwqx\App_KernelDevDebugContainer([
    'container.build_hash' => 'FiBxwqx',
    'container.build_id' => '5bf5757e',
    'container.build_time' => 1678016522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFiBxwqx');
